- name: Update Cloudflared on Debian
  hosts: cloudflare-daemons
  become: yes

  tasks:

    - name: Uninstall Cloudflared service
      command: cloudflared service uninstall
      become: yes
      ignore_errors: yes
      
    - name: Download Cloudflared package
      get_url:
        url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        dest: /tmp/cloudflared.deb

    - name: Install Cloudflared package
      apt:
        deb: /tmp/cloudflared.deb
        state: present

    - name: Configure Cloudflared service
      command: cloudflared service install {{ CLOUDFLARE_CONNECTOR_TOKEN }}

    - name: Remove downloaded Cloudflared package
      file:
        path: /tmp/cloudflared.deb
        state: absent